### ISSUE TITLE
no close button

### ISSUE THREAD

**Issue by lovesmilesha** [simply-coded/electron-navigation#1]
hello,can add a close button after UrlBar.  most likely chrome behavior?
https://raw.githubusercontent.com/simply-coded/electron-navigation/master/previews/light-theme.PNG

**Comment by simply-coded** [comment]
You will need to be more specific. I use Chrome and don't see any close button after the address bar. Could you take a picture of what you are talking about or Photoshop it and show me?

**Comment by simply-coded** [comment]
I'm closing this issue because more detail wasn't specified on what the issue actually is.
