### ISSUE TITLE
How do I change new tab button perform open a html file?

### ISSUE THREAD

**Issue by Wello6143** [simply-coded/electron-navigation#12]
Hi,
I want to say a huge thanks to you becasue this awesome module. But how do I change new tab button perform open a html file instead of opening Google page?
I found out that if I delete these line (on line 277):
```
else {
            url = (!url.match(/^[a-zA-Z]+:\/\//)) ? 'https://www.google.com/search?q=' + url.replace(' ', '+') : url;
        }
```
Then on line 144 I changed from 'http://google.com' to './index.html' it opened as I want. But if I open a new tab and search something, it not redirect me to google search page.
Thanks.

**Comment by simply-coded** [comment]
Just saw this now. To clarify, you want to be able to change the new tab button to whatever page you want, even a local one, but want to keep the google search functionality when entering text into the URL input. Correct?

**Comment by Wello6143** [comment]
How do I say thank you? <3

**Comment by simply-coded** [comment]
Just like that. Cheers.

**Comment by Wello6143** [comment]
Oh and btw, if change like this it not automatically open new tab when open the application? For example before your answer on my application: `enav.newTab('google.com');`

**Comment by Wello6143** [comment]
Also, if I do this, it not automatically open a new tab when I open my browser app. Before your help I used this: `// create a new tab to www.google.com
        enav.newTab('google.com');`

**Comment by Wello6143** [comment]
OK, after I take a closer look. If there is a <a> tag with open a site in new tab, it's will open a new tab but it's my html file, not that site.
Anyway for fix it?
Thanks!
