### ISSUE TITLE
When I open the new window page, it will be open a WebView on the right side of electron.

### ISSUE THREAD

**Issue by qinghua5453** [simply-coded/electron-navigation#15]
When I open the new window page, it will be open a WebView on the right side of electron.
In other words, the previous page is displayed at the same time.
er，in this situation, it will appear the above bug:
when I use `a` label and set its target="_blank"
the dependencies versions:

"electron": "^2.0.2",
"electron-navigation": "^1.5.8"

**Comment by simply-coded** [comment]
I'm unable to reproduce this error. Anymore details you can give me?

**Comment by qinghua5453** [comment]
ok.I am a Chinese.My english is poor.maybe i should show you my photos.
I sent an e-mail(simplycoded.help@gmail.com) to you.

**Comment by qinghua5453** [comment]
thanks very much.I later realized that it was the problem of the layout of the CSS。
Electron's WebView can't directly open new window needs. It's really a headache. Thank you for writing this modules. Sincerely hope that you are healthy and work smoothly.
thanks again.
