### ISSUE TITLE
Url isn't always updated

### ISSUE THREAD

**Issue by akz92** [simply-coded/electron-navigation#2]
I noticed that the url isn't always updated on `#nav-ctrls-url`. This happens when a tab is closed, when a link is clicked or a redirect happens.

Besides that, the value used doesn't always reflect the real address. For example when you search something directly from the url bar, Chrome's default behavior is to show the full url after the search (with `http://`).

I'm fixing these issues on [my fork](https://github.com/akz92/electron-navigation/tree/fix-url-update), I'd appreciate your feedback about it 🙂

**Comment by simply-coded** [comment]
Looks good. I'd be happy to merge it if you do a pull request.
