### ISSUE TITLE
Question: Why in demo2 does the nav icon turn red after webview is loaded?

### ISSUE THREAD

**Issue by Tam66662** [simply-coded/electron-navigation#20]
When I run demo2 using "npm run demo2", it loads YouTube url.  While it is loading, the nav icon is white and spinning. But when it is done, it turns red.  I cannot find any red setting in the css file that is making this turn red!  What is causing this?  I'd like to be able to control my icon color upon loading or changing the tab.

Thanks,
Tam

**Comment by codeartery** [comment]
The documentation says why. It get's the color from the normal favicon.
