### ISSUE TITLE
Bug: closableTabs option seems to be ignored

### ISSUE THREAD

**Issue by LightningBladeXYZ** [simply-coded/electron-navigation#4]
I am specifying the closableTabs option in my `const enav = new ElectronNavigation()`, however, while it does not ignore the `showAddTabButton: false`, it seems to like to ignore the closeableTabs. A picture is beneath for convenience:
![screenshot 33](https://user-images.githubusercontent.com/27926588/36838624-946af068-1d37-11e8-963f-e093d33ad6ed.png)

**Comment by simply-coded** [comment]
I have released a new version that fixes this issue. Thank you for pointing it out.
