### ISSUE TITLE
proxy settings are ignored

### ISSUE THREAD

**Issue by robsonhermes** [simply-coded/electron-navigation#8]
Hello
I am opening a new window in my Electron app and this new window uses electron-navigation. Before loading the html which contains the div/controls a proxy is being set:

    win.webContents.session.setProxy({proxyRules:"192.168.1.100:8080"},function(){
        console.log("changed proxy, now loading popup")
    });
    win.webContents.on('did-finish-load', () => {
        console.log("sending url to be loaded")
        win.webContents.send('url', url)
    });
    win.loadURL(`file://${__dirname}/windowWithNavigationControls.html`,NO_CACHE_OPTS);

Proxy is not being used.

However, if I go directly, without using electron-navigation, it goes through the proxy as expected:

    win.webContents.session.setProxy({proxyRules:"192.168.1.100:8080"},function(){
        console.log("changed proxy, now loading popup")
    });
    win.loadURL(url,NO_CACHE_OPTS);

**Comment by simply-coded** [comment]
To my knowledge you are just applying the proxy to the main page and not the webviews that reside in the page. A quick search pulled this up. I don't have time to test it though.  
https://discuss.atom.io/t/how-to-set-proxy-for-each-webview-tag-in-electronjs/37307/2

**Comment by robsonhermes** [comment]
I've found the problem. Forgot to set the partition of the webview to the same one where I was changing the proxy:

   <script>
      const enav = new (require('electron-navigation'))({defaultFavicons: true});

      require('electron').ipcRenderer.on('url', (event, message) => {
         enav.newTab(message, {
            title: 'default',
            icon: 'default',
            contextMenu: false,
            webviewAttributes: {partition:'persist:customerSite'}
         });
      })
   </script>

will close the issue
